development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: renju8920@gmail.com
  :password: appu@2014
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: renju8920@gmail.com
  :password: appu@2014
  :enable_starttls_auto: true